### ISSUE TITLE
server deleted the addon

### ISSUE THREAD

**Issue by georgew21** [jaruba/stremio-imdb-list#1]
Hello,

Unfortunately the server in which you had upload the two add-ons for stremio and imdb have deleted them.

Could you please upload them in another server?

thanks in advance.

**Comment by jaruba** [comment]
New endpoints:
- `https://imdb-list.baby-supernode.xyz/`
- `https://imdb-tag.baby-supernode.xyz/`
- `https://imdb-watchlist.baby-supernode.xyz/`
